### ISSUE TITLE
Show deployment failure log

### ISSUE THREAD

**Issue by hapaxlife** [denoland/deploy_feedback#209] opened 2022-05-14 14:54 UTC
Automatic Deployment fails with no detail/log in Github (production fail message only) ou dash.deno (no warning of failure)

I found the origin of the error when I unlik/link the project to repository

`Error The deployment failed: HTTP status client error (404 Not Found) for url (https://deno.land/std@/path/mod.ts)`

**Comment by ije** [comment] 2022-05-15 15:53
please try to change `https://deno.land/std@/path/mod.ts` ->  `https://deno.land/std@0.139.0/path/mod.ts`

**Comment by vwkd** [comment] 2022-05-21 11:53
I’m having a similar issue. The deployment fails, but the failure is only show in the GitHub Environments page without any error logs, and Deno Dashboard doesn’t even list the failed deployments. This makes it nearly impossible to figure out where the error in the code is.

**Comment by Joyzen** [comment] 2022-07-01 09:25
can deno/deploy show failure logs?
my project run local correct but deploy failure and I don't know why.

**Comment by niklasHagner** [comment] 2023-01-05 21:20
+1

I've got multiple commits on github.com in the past 7 days, some marked as :x: `Failed to deploy. See commit comment for more info`.
 
<img src="https://i.imgur.com/gjDRaa1.png" alt="github screenshot">

When I look through the commits there's no comments at all though.

And https://dash.deno.com/projects/my-project only shows two deploys in total, both from 7 days ago
<img width="761" alt="image" src="https://user-images.githubusercontent.com/3415677/210881307-e83fb3f4-c7d4-4341-8158-685cea8bb2f8.png">

**Comment by karfau** [comment] 2023-02-07 06:53
Same here, no trace of what the issue is for me, is there a way to trigger it manually to see what the issue is?
Currenlty I'm not able to deploy anything.

**Comment by capogreco** [comment] 2023-04-10 05:51
I am also having this problem.  Where can I find information about why my code is failing the check?

**Comment by audionerd** [comment] 2023-05-15 17:12
The GitHub API provides access to [Deployment status](https://docs.github.com/en/rest/deployments/statuses?apiVersion=2022-11-28) listings, and their `description` field will provide a failure message.

If you have GitHub CLI, you can list recent deployments with:

    gh api /repos/{owner}/{repo}/deployments

... and view the status of a deployment, and its `description` field, with

    gh api /repos/{owner}/{repo}/deployments/{deployment_id}/statuses

**Comment by arnauorriols** [comment] 2023-07-06 19:08
Hi everybody, we have added failed deployments to the deployments list, together with the error message, and the ability to see the build logs of all deployments. All this will be available going forward for new deployments (no retrofitting). I believe this covers all the feedback provided in this issue, right? I'm closing now, but feel free to reopen if you want to elaborate further.

**Closed by arnauorriols** 2023-07-06 19:08 UTC
Labels: enhancement
