### ISSUE TITLE
Node style import in deno workers.

### ISSUE THREAD

**Issue by Kartik4152** [denoland/deploy_feedback#389] opened 2023-05-15 19:43 UTC
I am using deno on supabase for edge functions.

I require the crypto library for some functionality, particularly (createCipheriv, createDecipheriv).
Before 0.178.0 I could import directly from the `std/node` directory, but since that was merged there is no way to import on deno workers.
The `node:` syntax is not supported on edge workers as it is not a valid url.
Is there any way to make node style imports work on workers?

**Comment by ry** [comment] 2023-05-15 21:17
It’s coming to Deno Deploy very soon now.

**Comment by satyarohith** [comment] 2023-05-20 06:33
Yes, `node:` will come soon along with `npm:`. Closing this as a duplicate of https://github.com/denoland/deploy_feedback/issues/314

**Closed as completed by satyarohith** 2023-05-20 06:33 UTC
