### ISSUE TITLE
Logs view fails after 1 minute

### ISSUE THREAD

**Issue by cknight** [denoland/deploy_feedback#196] opened 2022-05-03 14:12 UTC
This is affecting the new design.  When visiting the logs page and leaving it open for at least 1 minute, the logs are replaced with a network error message ("network error").  Likely cause is this fetch URL for my project being called:
```
GET | https://dash.deno.com/_api/projects/d7e61e67-4a83-46ca-96bb-70d05ea9e277/deployments/latest/logs
```
Interestingly, it responds with a 200 with valid looking content, but only after a minute has gone by.  This is in Firefox v99.0.1.

**Comment by ije** [comment] 2022-05-03 14:13
thanks, i will look into it!

**Comment by magurotuna** [comment] 2023-04-19 00:45
I was unable to reproduce this problem, so I'm going to close the issue. Please let us know if it's still a problem.

**Closed by magurotuna** 2023-04-19 00:45 UTC
