### ISSUE TITLE
Cannot deploy deno project with scoped npm module

### ISSUE THREAD

**Issue by sgohlke** [denoland/deploy_feedback#316] opened 2022-11-26 21:45 UTC
I tried to link my project https://github.com/sgohlke/deno-graphql/ (entry point: webserver.ts) to Deno Deploy and got an error 
"Error The deployment failed: Module not found "npm:@dreamit/graphql-server@3.0.0".". I tried with both "npm:@dreamit/graphql-server" and "npm:@dreamit/graphql-server@3.0.0" but it does not deploy. Locally it is working fine.

**Comment by mehmetuken** [comment] 2022-11-30 16:15
Deploy has no support yet npm packages.

https://deno.com/blog/npm-and-deno-anywhere

> Yes, [Deno Deploy](https://deno.com/deploy) is an excellent choice to host your Deno code, especially if you want it to be executed close to your users on [the edge](https://deno.com/blog/the-future-of-web-is-on-the-edge). Deploying to [our V8 isolate cloud](https://deno.com/blog/anatomy-isolate-cloud) takes seconds and can be accessed around the world within seconds. **Also, npm specifiers aren't currently supported in Deploy, but will be soon.**

**Comment by satyarohith** [comment] 2023-02-13 07:30
Duplicate of #314

**Closed by satyarohith** 2023-02-13 07:30 UTC
