### ISSUE TITLE
Deno deploy down?

### ISSUE THREAD

**Issue by jakearchibald** [denoland/deploy_feedback#109] opened 2021-10-12 17:59 UTC
https://cors-playground.deno.dev/ can't be reached, and I'm not seeing anything in the logs.

**Comment by lucacasonato** [comment] 2021-10-12 18:35
After initial investigation it looks like the cause was some fallout from a deployment we landed a few hours ago. Everything should up and running normally now.

**Closed as completed by lucacasonato** 2021-10-12 18:35 UTC
