### ISSUE TITLE
How to use importmaps with deployctl+git integration

### ISSUE THREAD

**Issue by fusionstrings** [denoland/deploy_feedback#17] opened 2021-03-30 15:07 UTC
First of all I am grateful that this service came to existence. Thanks a lot for all the people behind it.
I have been trying it out with one of my projects with this file https://github.com/fusionstrings/chitrkatha/blob/7778002e6cb19c79840a65fe6d1c7f1da118e9ec/src/server.ts as starting point.

This uses importmap but I didn't find any way to use importmap with Deno Deploy directly. 

P.S. I understand that there are workarounds to it i.e. creating an intermediate file and use `Deno.run` but I wonder if there is a direct way.

**Comment by forgo** [comment] 2021-04-24 23:51
I have the same question. I was under the assumption that having `import_maps.json` at the root of my git repo would just work, but I think that's not yet the case. Or have I overlooked some documentation?

**Comment by ChristianSiegert** [comment] 2021-05-01 15:32
Import maps are currently not supported in Deno Deploy but will be in the future (see [API Reference](https://deno.com/deploy/docs/runtime-api#future-support), section “Future support”, bullet point “Import Maps”).

**Comment by bobvanderlinden** [comment] 2022-01-08 20:26
I was trying to deploy my first Deno project to Deno deploy, but ran into this issue. I'm a bit split between using a single deps.ts file or import-map. Are import-maps not supported yet because they are not the recommended way to go?

Has there been some progress in this regard?

**Comment by lucacasonato** [comment] 2022-03-23 16:21
Import maps are now supported in the `deployctl` / GitHub Actions flow by specifying the `--import-map` flag for `deployctl`, or the `import-map:` option in the `with:` block of the deployctl GitHub Action.

Support for import maps discovered via the `deno.json`/`deno.jsonc` file is coming soon to regular GitHub deployments.

**Closed by lucacasonato** 2022-03-23 16:21 UTC

**Comment by hyp3rflow** [comment] 2022-06-02 06:05
@lucacasonato Is there any update for import map support on regular GitHub deployments?

**Comment by satyarohith** [comment] 2022-06-02 06:46
Hi @hyp3rflow, the support has been introduced recently. Here's a working example: https://github.com/satyarohith/import_map

**Comment by hyp3rflow** [comment] 2022-06-02 07:33
> Hi @hyp3rflow, the support has been introduced recently. Here's a working example: [satyarohith/import_map](https://github.com/satyarohith/import_map)

Oh I didn't notice that. thanks! @satyarohith

**Comment by osdiab** [comment] 2022-09-09 06:25
hm @satyarohith is there anything I need to do to make this work by default? I just tried it as well with the Fresh template, which includes a `deno.json` with `importMaps` specified, and that doesn't seem to work.

**Comment by patreeceeo** [comment] 2023-02-05 19:51
I'm also having trouble with using import maps in Deno Deploy. I've set up an `importMap` (singular) in my `deno.json` and created an import_map.json per the example, but Deno Deploy says:

```
Relative import path "http" not prefixed with / or ./ or ../
```

My project is very simple right now, I'll make a clone of it and perhaps that can serve as a minimal reproducing example?
https://github.com/patreeceeo/deno-deploy-import-map-error

**Comment by patreeceeo** [comment] 2023-02-05 19:58
Got it to work by add `import-map` to the Github workflow yaml per https://github.com/denoland/deploy_feedback/issues/17#issuecomment-1076532539

**Comment by th0rgall** [comment] 2023-03-04 16:51
I got the relative import error when using an `imports` key in my `deno.jsonc`.

What fixed it was moving the `imports` into their own `import_map.json` file and referencing them from the config file with `"importMap": "./import_map.json"`, as suggested in https://github.com/denoland/deploy_feedback/issues/17#issuecomment-1144500521.

Directly having import map support from `deno.jsonc` too would be nice!
