### ISSUE TITLE
Deno.version gives empty strings on Deno Deploy playground

### ISSUE THREAD

**Issue by rattrayalex** [denoland/deploy_feedback#533] opened 2023-10-26 00:45 UTC
At https://dash.deno.com/playground/

Input:
```ts
console.log(Deno.version)
```
Output:
```
gcp-us-east4 { deno: "", v8: "", typescript: "" }
```
Expected: 
```
{ deno: "1.37.2", v8: "11.8.172.13", typescript: "5.2.2" }
```
(or equivalent)

**Comment by fro-profesional** [comment] 2023-10-27 09:36
Deno cli and deno deploy are not the same runtime

**Comment by rattrayalex** [comment] 2023-10-27 18:34
Ah, sorry, thank you for forwarding to the correct location!

**Comment by adamtaylor13** [comment] 2023-11-14 18:54
Note that this is not limited to the playground: https://github.com/denoland/deploy_feedback/issues/437

**Comment by satyarohith** [comment] 2024-01-02 14:46
Closing this as duplicate of https://github.com/denoland/deploy_feedback/issues/437

**Closed as not planned by satyarohith** 2024-01-02 14:46 UTC
