### ISSUE TITLE
[Bug]: HTTP status client error (404 Not Found) for url (https://deno.land/x/supabase@v2.24.0/mod.ts)

### ISSUE THREAD

**Issue by dandaka** [denoland/deploy_feedback#420] opened 2023-07-02 13:31 UTC
### Problem description

I have a project, that is using Supabase. No changes were made to the code that works with Supabase. For some reason, deploy has broken. The project is working as expected on a local machine.

When I am trying to deploy, I get this error

> HTTP status client error (404 Not Found) for url (https://deno.land/x/supabase@v2.24.0/mod.ts)

This is strange since I am not using this URL to import. I link to supabase in a few places in the code

1/ import { createClient } from "https://esm.sh/@supabase/supabase-js@2.10.0";
2/ package.json
    "@supabase/supabase-js": "^2.10.0",
3/ import { supabaseAdapter } from "https://deno.land/x/grammy_storages@v2.0.0/supabase/src/mod.ts"; 

In a few workarounds (https://github.com/denoland/deno_std/issues/3256), I have seen that I need to use import_map.json to rewrite the URL. Not sure, what to put there.

### Steps to reproduce

push to my github repo
deno deploy tries to download the code to run it
the above error stops the deploy

### Expected behavior

1/ Deno Deploy works the same way as the local machine

2/ If there is a need to manually add some workarounds, they are available in the documentation

3/ Deploy does not break existing projects when introduces changes

### Environment

macOS Version 13.2.1 (22D68)
Current Deno version 1.31.3
Current TypeScript version 4.9.4
Current V8 version 11.0.226.19

**Comment by lucab** [comment] 2023-07-03 07:58
Thanks for the report.
I think the problem is coming from this import in the `grammy_storages` library: https://github.com/grammyjs/storages/blob/v2.0.0/packages/supabase/src/deps.deno.ts#L1.
I'm not familiar with this library, so I'd suggest talking to its author to find out what's going on.

I'm not sure why you get a different behavior locally, but possibly you have some previous code versions cached or you are using a different entrypoint when running the project. In general, the [Deno dependency inspector](https://deno.land/manual@v1.34.3/tools/dependency_inspector) may be useful to get a better view of the full tree of transitive dependencies.

I'm closing this ticket, as it doesn't seem to be a problem with Deno Deploy specifically.

**Closed as completed by lucab** 2023-07-03 07:58 UTC
