### ISSUE TITLE
[KV Feedback]: I seem to have broken the online KV ui

### ISSUE THREAD

**Issue by kewp** [denoland/deploy_feedback#558] opened 2023-12-06 10:09 UTC
### 🔍

- [ ] Did you search for existing issues?

### Type of feedback

Bug report

### Description

Not sure why, but my KV page won't load. https://dash.deno.com/projects/ucn-prices-api/kv

### Steps to reproduce (if applicable)

Click on page https://dash.deno.com/projects/ucn-prices-api/kv
Wait forever

### Possible solution (if applicable)

Maybe I have too much data? Not sure

**Comment by losfair** [comment] 2023-12-06 10:29
Duplicate of https://github.com/denoland/deploy_feedback/issues/557.

A recent rollout caused the KV tab to stop working. This has been fixed.

**Closed as not planned by losfair** 2023-12-06 10:29 UTC
Labels: kv

**Comment by kewp** [comment] 2023-12-06 11:19
Yup, it's working now. Thanks
