### ISSUE TITLE
Error while viewing deploy log page.

### ISSUE THREAD

**Issue by nhrones** [denoland/deploy_feedback#198] opened 2022-05-03 14:32 UTC
While viewing logs in a log page, The page refreshed with a network error report in the log container.
<img width="748" alt="log-error" src="https://user-images.githubusercontent.com/3278787/166473202-7b7dabae-463b-46f3-b21e-ffde76aa7928.png">

Refreshing the page showed the normal view of the logs again.

This seems to happen repeatedly while viewing 
`https://dash.deno.com/projects/fresh-dice-rtc/logs `

**Comment by piscisaureus** [comment] 2023-03-30 22:18
Duplicate of #196.

**Closed by piscisaureus** 2023-03-30 22:18 UTC
