### ISSUE TITLE
import map embedded in deno.json not supported

### ISSUE THREAD

**Issue by uriva** [denoland/deploy_feedback#344] opened 2023-03-13 21:51 UTC
```
Error The deployment failed: Module not found "npm:@noble/hashes/sha256".
```

this is what I got, but locally deno does find the target

**Comment by uriva** [comment] 2023-03-14 14:32
https://stackoverflow.com/questions/75734520/using-paulmillr-noble-secp256k1-with-deno-deploy

**Comment by jupegarnica** [comment] 2023-03-14 14:38
@uriva deno deploy doesn`t support npm specifiers yet
https://deno.com/blog/npm-and-deno-anywhere

**Comment by uriva** [comment] 2023-03-14 14:39
Ok but is there some simple recipe to do it in this case?

**Comment by jupegarnica** [comment] 2023-03-14 14:42
try cnds,   it could work
https://deno.land/manual@v1.31.2/node/cdns

**Comment by uriva** [comment] 2023-03-14 15:41
someone helped me (can see answer) - this was really not obvious to me as a beginner...

thanks!

**Comment by uriva** [comment] 2023-03-14 15:45
actually, still doesn't work.

maybe because deno deploy doesn't understand where my deno.json is?

repo is uriva/portal
the file i'm linking is `hub/src/index.ts`

**Comment by uriva** [comment] 2023-03-14 15:46
I tried placing the deno.json near the index.ts and also in the root on both attempts I got 

```
Error The deployment failed: Relative import path "crypto" not prefixed with / or ./ or ../
```

**Comment by magurotuna** [comment] 2023-03-29 15:10
Thanks for reporting the issue. Unfortunately Deno Deploy doesn't currently support import map embedded in deno.json although it's been supported since Deno v1.30. We will be working on adding the support to Deploy.

**Comment by piscisaureus** [comment] 2023-03-30 21:17
Duplicate of #314.

**Comment by magurotuna** [comment] 2023-03-31 01:17
No this issue is now not a duplicate of #314. The topic has changed to the lack of support for import map embedded in deno.json. I'm going to reopen it and to change the title to make it clear.

**Comment by wesbos** [comment] 2023-04-18 14:12
Also hit this - using "import" in `deno.json`. Works great locally, but fails on deno deploy. 

The fix is to create a separate import_map.json, and reference it via "importMap" key in `deno.json`.

Deno Deploy should work 1:1 with my local dev, especially with something that is recommended in the deno docs. small thing, but it's one of those tripping hazards that makes people go back to node

**Comment by magurotuna** [comment] 2023-04-25 06:30
We're aware that the inconsistency between CLI and Deploy is so annoying, and we're working on resolving it.

**Comment by magurotuna** [comment] 2023-06-02 07:42
Import maps embedded in `deno.json(c)` is now supported. It's auto-discovered and serves as if it were a separate `import_map.json`.

**Closed by magurotuna** 2023-06-02 07:42 UTC
Labels: bug
