### ISSUE TITLE
[Bug]: I am not able to invite users to my organization

### ISSUE THREAD

**Issue by zbynekwinkler** [denoland/deploy_feedback#442] opened 2023-07-21 08:16 UTC
### Problem description

I am not able to invite users to my organization. When I try I get an API error.

### Steps to reproduce

1. create organization
2. go to settings > members
3. click Invite Member and fill github user name

Result is API error that disappears the moment I click it so I am unable to copy the text to paste here. The best I could do is a screenshot:

![image](https://github.com/denoland/deploy_feedback/assets/1130051/d4ce2e82-fc66-499d-976c-036fc5a4ebee)

Direct link: https://dash.deno.com/orgs/f04b44d4-e58e-4ba2-aa12-10233aea50db/settings#members
Users I tried to invite: luciusb, pavliik

### Expected behavior

No error and the users are invited.

### Environment

Vivaldi browser on Windows 11.

**Comment by arnauorriols** [comment] 2023-07-21 08:40
Hi @zwn. The users must first sign into Deploy before they can be invited to organizations. We are evaluating the possibility to relax this requirement and invite users that are not yet in Deploy. Closing as duplicate of #271. Feel free to 👍 that issue to show that you share the same concern.

**Closed as completed by arnauorriols** 2023-07-21 08:40 UTC

**Comment by zbynekwinkler** [comment] 2023-07-21 09:26
A possible UX improvement could be a change in the wording of the error suggesting that we ensure the users have already signed up for Deploy. The way it is now it just invites everyone who sees it to submit an issue.
