### ISSUE TITLE
Only a fixed number of branches are listed

### ISSUE THREAD

**Issue by roj1512** [denoland/deploy_feedback#174] opened 2022-02-20 18:04 UTC
When I try to deploy an app from a repository with too many branches, only a fixed number of branches are listed in this select. Please fix it ASAP. 

![](https://cdn.discordapp.com/attachments/826085979344470037/943476714456113194/IMG_6057.png)

**Comment by satyarohith** [comment] 2022-03-01 16:49
@roj1512, the issue is now fixed. Thanks!

**Closed by satyarohith** 2022-03-01 16:49 UTC

**Comment by roj1512** [comment] 2022-03-01 16:53
Super awesome!
