### ISSUE TITLE
[KV Feedback]: DENO_KV_ACESS_TOKEN typo

### ISSUE THREAD

**Issue by timreichen** [denoland/deploy_feedback#549] opened 2023-11-22 15:56 UTC
### 🔍

- [ ] Did you search for existing issues?

### Type of feedback

Bug report

### Description

Under `KV(Beta)->Connect to this database from Deno CLI` the description says `DENO_KV_ACESS_TOKEN ` instead of `DENO_KV_ACCESS_TOKEN`.

**Comment by magurotuna** [comment] 2023-11-23 06:57
Thank you for reporting that. This issue is duplicate of #545 so please watch #545 for updates

**Closed as completed by magurotuna** 2023-11-23 06:57 UTC
Labels: kv
