### ISSUE TITLE
BroadcastChannel betwen EU and US regions

### ISSUE THREAD

**Issue by bolchowka** [denoland/deploy_feedback#263] opened 2022-08-11 15:27 UTC
Hello,
I deployed my app on Deno Deploy. I'm trying to synchronise app state between regions with [BroadcastChannel API](https://deno.com/deploy/docs/runtime-broadcast-channel). I am connected to a websocket on two browsers: one in `europe-central2` region, second in `us-east4`. Messages sent from Europe are correctly received by BroadcastChannel `onmessage` handler in US. However, messages sent from US to EU are not received.

I can reproduce the same problem on the Deno Chat demo: https://denochat.deno.dev/. I'm connected to `europe-central2` without VPN, and to `us-east4` through Tunnelbear. Messages from EU are received by US, but not the other way.

Is this a known issue?

**Comment by bolchowka** [comment] 2022-08-12 23:32
I have just tested this again and the problem is gone. Both regions communicate well with each other.

Could that be some infrastructure problem?

**Comment by bolchowka** [comment] 2022-08-24 11:53
The problem unfortunately persists.

I'm now experiencing problem with `asia-east1` instance. Messages sent from this instance are correctly received in other regions, but no messages sent from other regions reach `asia-east1`. Some regions in Europe also experience the same buggy behaviour.

Is there anything I could do to fix this deliverability problem?

**Comment by piscisaureus** [comment] 2022-08-24 21:38
The Deno Deploy team is looking into this issue.

**Comment by nesk** [comment] 2022-09-13 21:56
I can confirm the problem persists, I'm currently trying to broadcast some messages from the `us-east4` region to the `europe-west8` one, but I receive nothing. Until today, it worked fine. Last time I remember testing this and seeing it work was the 8th September.

Did you make any progress on your side?

If you need any help to reproduce the issue, just let me know.

**Comment by CetinSert** [comment] 2022-09-14 05:17
> @bolchowka – this is still occurring between, at least, `us-east5` and `asia-northeast3`.

This still persists too.

**Comment by nesk** [comment] 2022-09-14 11:52
FYI, it seems rather erratic, today it works while yesterday it wasn't. 😅

**Comment by nesk** [comment] 2022-09-25 21:02
One more thing: this issue doesn't seem related to a broken deployment. A few hours ago, I've deployed a new version of my app, and the broadcasting from `us-east4` to `europe-west8` wasn't working. I've just tried once again right now, without deploying, and now it works. Note that the isolates have been shut down in between, fresh ones were started on my last test.

Did the Deno team made any progress on this? It's been one month since the last official message on the subject. It would be reassuring to hear about the team.

**Comment by OzySky** [comment] 2022-10-03 21:21
Bump @piscisaureus

**Comment by jakeg** [comment] 2022-11-13 02:48
Was this issue resolved? I intend to try out `BroadcastChannel` tomorrow which will be required to move my web app from Heroku to Deploy, but it's a non-starter if it's not working.

**Comment by CetinSert** [comment] 2022-12-21 11:58
Any updates?

**Comment by CetinSert** [comment] 2023-02-01 09:27
@piscisaureus – any progress?

**Comment by piscisaureus** [comment] 2023-02-01 09:29
@CetinSert does BroadcastChannel still not work right?

**Comment by ry** [comment] 2023-04-07 00:45
Should be fixed now, although https://denochat.deno.dev/ is broken.

**Closed by ry** 2023-04-07 00:45 UTC

**Comment by CetinSert** [comment] 2023-04-07 11:39
This is still not working. Is this getting deployed slowly?

**Comment by cirolosapio** [comment] 2026-08-15 22:04
Is this still an issue on the new Deno Deploy? Specifically: if I deploy an app on the free tier with default regions (global, i.e. both us and eu) and use native WebSockets, will messages sent via BroadcastChannel (or any equivalent mechanism) fail to propagate between regions/instances the same way described here? The new Deploy docs don't mention BroadcastChannel at all outside the Classic section, so it's unclear if it still exists, was removed, or just isn't documented yet.
