### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by wdalhaj** [denoland/deploy_feedback#719] opened 2024-09-26 12:46 UTC
### What problem are you trying to solve?

I have photophobia (light sensitivity), current theme is too bright for me, especially with too much empty spaces in ui.

### Describe the solution you'd like

enabledark mode option. 

### Describe alternatives you've considered

using dark mode browser plugins?

**Comment by marvinhagemeister** [comment] 2024-09-26 12:47
Duplicate of https://github.com/denoland/deploy_feedback/issues/82

**Closed as completed by marvinhagemeister** 2024-09-26 12:47 UTC
Labels: enhancement
