### ISSUE TITLE
Cannot use Deno.stat() get file's metadata

### ISSUE THREAD

**Issue by champkeh** [denoland/deploy_feedback#191] opened 2022-04-23 04:02 UTC
I want to use the `Deno.stat()` to get a file's last mod time, but the api result is 
```json
{
  "atime": null
  "birthtime": null
  "blksize": null
  "blocks": null
  "dev": null
  "gid": null
  "ino": null
  "isDirectory": false
  "isFile": true
  "isSymlink": false
  "mode": 292
  "mtime": null
  "nlink": null
  "rdev": null
  "size": 1417
  "uid": null
}
```

Only few fields has value.

I want to get a data file's last mod time so I can display the `updateAt` information in the website page.

**Comment by lucacasonato** [comment] 2023-07-05 14:16
Closing as duplicate of #334

**Closed by lucacasonato** 2023-07-05 14:16 UTC
