### ISSUE TITLE
Does Deno Deploy shutdown my apps if there's no incoming request ?

### ISSUE THREAD

**Issue by implicitdef** [denoland/deploy_feedback#143] opened 2021-12-19 19:52 UTC
Hi

I tried to use Deno Deploy to run some kind of task every day at a fixed time, like a cron. So it's a small program that doesn't need to answer to any incoming requests, just to keep running.
It ran fine at the first deploy but then the next day it didn't. I have not finished debugging yet but I'm starting to suspect Deno Deploy just puts the process to sleep if there's no request, or something like that ?

If that's the case that's perfectly understandable, but it should be clearly stated in the docs.

**Comment by bnoordhuis** [comment] 2021-12-19 23:35
It's mentioned on the https://deno.com/deploy/docs/pricing-and-limits page:

> Isolate: an instance of your deployment running in any one of the available regions. Isolates are created and destroyed on demand based on traffic to your deployment.

Instances can be terminated at any time when they're not receiving traffic.

**Comment by implicitdef** [comment] 2021-12-20 11:15
Ok, I read that page but must have skipped over that paragraph. The formatting makes it seem like just a small technical definition or a side note.

I think you could should make it more obvious, include some wording for it in the landing page https://deno.com/deploy/docs.
I'm more familiar with stuff like Heroku where my app keeps running all the time, and when I read this landing page for Deno Deploy I see nothing that suggests a difference.

**Comment by AaronO** [comment] 2021-12-20 11:29
@implicitdef Btw we're looking to add first class support for cron tasks. This would be distinct from setTimeout/setInterval since those are inefficient at scale and don't fit well in a multi-isolate/multi-region model.

**Comment by nhrones** [comment] 2022-02-15 04:42
@AaronO Any suggestion for a duration for a keepalive heartbeat?  I've had so many problems with deploy disconnects, that I now just use Deploy-WS->BC as a signal server to negotiate a WebRTC DataChannel. 
I then just ignore the Deploy instance.

**Comment by vwkd** [comment] 2022-02-26 19:35
@nhrones The point of FaaS is exactly to not keep an instance running during idle. 

Instead, Deno Deploy should likely optimize startup time (e.g. 0s like Cloudflare Workers by starting up already during TLS handshake) and provide a Storage API to persist data (#110)

**Comment by nhrones** [comment] 2022-02-27 01:49
@vwkd If so, why even provide WebSocket and BroadcastChannel?  There currently is no persistance in Deploy, So it is currenly only a fancy CDN!

**Comment by in64** [comment] 2022-04-01 05:08
would like to support  cron job, like
https://developers.cloudflare.com/workers/platform/cron-triggers/

**Comment by janek** [comment] 2022-09-16 08:07
I agree that it would be nice to make this more clear in the docs, I only found out after finding this issue. And I think for new users without previous experience with Heroku, this could be quite confusing - my Telegram bot just stopped working, and for some reason writing to it doesn't "wake up" the deployment.

**Comment by RikuTheFuffs** [comment] 2022-09-29 08:32
Hey everybody, I have a Discord bot deployed on Deno that seems to just stop after some udnefined time. Point is, I use this bot to hand out keys of a game to the new users of my Discord, so if it fails sending them they can't do anything 😭

My understanding is that the deploy instance should automatically start up whenever somebody enters the server (= a request is sent). 
1. Why is this not happening, on Deno? 
2. And is there any way to keep the bot active? 
3. And how much does it take to shut itself down?

**Comment by janek** [comment] 2022-09-30 14:27
1. I'm not sure if I understand/remember correctly, but it could be that it doesn't actually send a http request to your bot when someone enters. In the case of my Telegram bot, I'm polling for updates, so a new message from a user doesn't mean that the Deno instance gets a request. If I'd done my bot with webhooks, it would work as intended (see https://grammy.dev/guide/deployment-types.html if curious).

2. As a sanity check, see if going to https://your-thing.deno.dev wakes it up or not. If it does, you can use UptimeRobot or similar to trigger that every 5-10 minutes. Make sure to use `https` and not `ping` as "monitor type". See screenshot:

<img width="595" alt="Screenshot 2022-09-30 at 16 11 31" src="https://user-images.githubusercontent.com/2146927/193291897-afe6ee3c-dc47-4598-8a99-5a47e7e91a01.png">


3. I think it's pretty short, like 10-20mins - but I could be wrong.

This is a workaround, but it should help.

**Comment by harrysolovay** [comment] 2023-05-17 10:01
@nhrones makes a good point:

> why even provide WebSocket and BroadcastChannel?

Any guidance on using these features and ensuring that they're not preemptively terminated?

**Comment by lucacasonato** [comment] 2023-07-05 14:08
The original issue has been resolved, so I'll close this issue. Thank you :)

**Closed by lucacasonato** 2023-07-05 14:08 UTC
